### ISSUE TITLE
Expose the underlying server

### ISSUE THREAD

**Issue by flasaracina** [titoBouzout/angelia.io#63]
Hello!
I really like this library! I'd like to ask you if ii is possible to have it with a "no server" option or if it is possible to access the underlying http server the library is using for further customization.

Thanks

**Comment by titoBouzout** [comment]
Hey! I will expose the underlying http server meanwhile I think how to make it work with a "no server" option.

**Comment by flasaracina** [comment]
Thanks! Looking forward to it

**Comment by titoBouzout** [comment]
There's an update.  You can access the underlying `http` server via the property `Server.http`  (after calling `Server.listen(..)`)

If you want to give a server, pass it as an option:

```js
Server.listen({
	hostname: 'localhost',
	port: 3001,
	http: require('http').createServer()
})
```

I'm not completely sure what's your use case for this, or how can it be used. I would be interested to hear about, a small snippet maybe illustrating the idea. If you need anything else, let me know.

**Comment by flasaracina** [comment]
Oh, Thanks!
The use case would be to use the socket server alongside a normal http server to handle specific routes that should be served with the usual http / https protocol.

Think about chat applications, web games, etc. You may want to have "normal" routes to handle static assests like HTML / CSS / JS and / or backend routes for authentication / authorization, etc.
At the end of the day even with a socket server like angelia.io, the client is starting the communication by using http that gets upgraded ( HTTP status 101 switching protocol ) to instruct both parts that from that moment on they will be using the websocket protocol
